{% set name = "pyextremes" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/georgebv/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4b43aa0be55f3806b66525c5439f6547c109b389a172a1b165cbf41157baf28b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .[full] -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - emcee >=3.0
    - matplotlib-base >=3.3
    - numpy >=1.19
    - pandas >=1.0
    - scipy >=1.5
    - tqdm >=4.0,<5

test:
  imports:
    - pyextremes
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest

about:
  home: https://github.com/georgebv/pyextremes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extreme Value Analysis (EVA) in Python
  description: pyextremes is a Python library aimed at performing univariate Extreme Value Analysis (EVA).
  dev_url: https://github.com/georgebv

extra:
  recipe-maintainers:
    - georgebv
