{% set name = "pyextremes" %}
{% set version = "2.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/georgebv/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 01b0bed6cbf075b5439405e4c15772f9b04756d2db349ef4f54a04a3029dc069

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .[full] -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - emcee >=3.0
    - matplotlib-base >=3.3
    - numpy >=1.19
    - pandas >=1.0
    - scipy >=1.5
    - tqdm >=4.0,<5

test:
  imports:
    - pyextremes
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest

about:
  home: https://github.com/georgebv/pyextremes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extreme Value Analysis (EVA) in Python
  description: pyextremes is a Python library aimed at performing univariate Extreme Value Analysis (EVA).
  dev_url: https://github.com/georgebv

extra:
  recipe-maintainers:
    - georgebv
