{% set name = "pyextremes" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/georgebv/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5f827ac882b40019369bfd27a77d45ff6047454542c617e879a0ec7734224de8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .[full] --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - uv
    - uv-build
  run:
    - python >={{ python_min }}
    - emcee >=3.0,<4
    - matplotlib-base >=3.3,!=3.9.1,<4
    - numpy >=1.19,<3
    - pandas >=1.0,<3
    - scipy >=1.5,<2
    - tqdm >=4.0,<5
    - lmoments >=1.0.8,<2

test:
  imports:
    - pyextremes
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest

about:
  home: https://github.com/georgebv/pyextremes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extreme Value Analysis (EVA) in Python
  description: pyextremes is a Python library aimed at performing univariate Extreme Value Analysis (EVA).
  dev_url: https://github.com/georgebv

extra:
  recipe-maintainers:
    - georgebv
