{% set name = "pyextremes" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 954f4f2db79bf2aed2bf97cd787e80697ee9d4f35ca999a4ffe6a5eb37a28c5d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - emcee >=3.0
    - matplotlib-base >=3.3
    - numpy >=1.19
    - pandas >=1.0
    - scipy >=1.5

test:
  imports:
    - pyextremes
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest

about:
  home: https://github.com/georgebv/pyextremes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extreme Value Analysis (EVA) in Python
  description: |
    pyextremes is a Python library implementing an easy-to-use extensible framework
    used to perform Extreme Value Analysis (EVA).
    It provides tools necessary to perform typical tasks constituting EVA, such as:
    extraction of extreme events from time series using Block Maxima or Peaks Over Threshold methods;
    fitting continuous distributions, such as GEV, GPD, or user specified continous distribution, to the extracted extreme events;
    visualization of model performance and goodness-of-fit statistics;
    estimation of extreme events of given probability (e.g. 100-year event) and corresponding confidence intervals;
    tools assisting with model selection and tuning (block size in BM, threshold in POT);
    (work-in-progress) multivariate extreme value analysis;
  dev_url: https://github.com/georgebv

extra:
  recipe-maintainers:
    - georgebv
